version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Editlio.Web/Dockerfile
    ports:
      - "8080:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_API_URL=http://api:7273
      - ConnectionStrings__DefaultConnection=Server=mssql;Database=EditlioDb;User=sa;Password=${MSSQL_SA_PASSWORD};TrustServerCertificate=True;Encrypt=False;
    depends_on:
      - api
      - mssql
    networks:
      - editlio-network

  api:
    build:
      context: .
      dockerfile: Editlio.Api/Dockerfile
    ports:
      - "7273:7273"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultConnection=Server=mssql;Database=EditlioDb;User=sa;Password=${MSSQL_SA_PASSWORD};TrustServerCertificate=True;Encrypt=False;
    depends_on:
      - mssql
    networks:
      - editlio-network

  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: mssql-container
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "${MSSQL_SA_PASSWORD}"
      ACCEPT_EULA: "Y"
    networks:
      - editlio-network

networks:
  editlio-network:
    driver: bridge
    name: editlio-network
