version: '3.8'

services:
  web:
    build:
      context: .
      target: web
    ports:
      - "5000:5000"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:5000
      - ConnectionStrings__DefaultConnection=Server=db;Database=EditlioDb;User Id=sa;Password=${DB_PASSWORD};TrustServerCertificate=True
      - ApiSettings__BaseUrl=http://api:5001
      - AppSettings__RealtimeHubUrl=http://api:5001/hubs/realtime
    depends_on:
      - db
      - api
    networks:
      - editlio-network
    restart: always

  api:
    build:
      context: .
      target: api
    ports:
      - "5001:5001"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultConnection=Server=db;Database=EditlioDb;User Id=sa;Password=${DB_PASSWORD};TrustServerCertificate=True
    depends_on:
      - db
    networks:
      - editlio-network
    restart: always 

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=${DB_PASSWORD}
      - MSSQL_PID=Express
    ports:
      - "1433:1433"
    volumes:
      - sqldata:/var/opt/mssql
    networks:
      - editlio-network
    restart: always 

networks:
  editlio-network:
    driver: bridge

volumes:
  sqldata:
