version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Editlio.Web/Dockerfile
    ports:
      - "8080:80"
      - "8443:443"  
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_API_URL=https://localhost:7273
      - ASPNETCORE_URLS=http://localhost:80;https://localhost:443
      - ConnectionStrings__DefaultConnection=Server=mssql;Database=EditlioDb;User=sa;Password=MssqlSecure#123;TrustServerCertificate=True;Encrypt=False;
    depends_on:
      mssql:
        condition: service_healthy
      api:
        condition: service_healthy
    networks:
      - editlio-network

  api:
    build:
      context: .
      dockerfile: Editlio.Api/Dockerfile
    ports:
      - "7273:7273"
      - "7443:443"  
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://localhost:7273;https://localhost:443
      - ConnectionStrings__DefaultConnection=Server=mssql;Database=EditlioDb;User=sa;Password=MssqlSecure#123;TrustServerCertificate=True;Encrypt=False;
    depends_on:
      mssql:
        condition: service_healthy
    networks:
      - editlio-network

  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: mssql-container
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "MssqlSecure#123"
      ACCEPT_EULA: "Y"
    networks:
      - editlio-network
    volumes:
      - mssql_data:/var/opt/mssql
    healthcheck:
      test: ["CMD-SHELL", "sqlcmd -U sa -P MssqlSecure#123 -Q 'SELECT 1' || exit 1"]
      interval: 10s
      retries: 3
      start_period: 30s

networks:
  editlio-network:
    driver: bridge
    name: editlio-network

volumes:
  mssql_data:
    driver: local
